version: '3.3'

services:
  app:
    image: mocked-${BB_NAME:-bb}-image
    ports:
      - 3333:3000
    networks:
      - web
    build:
      context: ./../../
      dockerfile: ./examples/mockoon/Dockerfile

networks:
  web:
    driver: bridge